
Elo = require('elo-js')
_ = require('lodash')
Table = require('easy-table')
Npl = require('nodeplotlib')

const data = [
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U8M0TKXV0", "loser_name": "kim.stebel" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U8NPFQK6U", "loser_name": "sergio.martin" },
  { "winner_id": "UKPKALVKM", "winner_name": "pedro.ferreira", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "UKPKALVKM", "winner_name": "pedro.ferreira", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U8M0TKXV0", "loser_name": "kim.stebel" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "UKPKALVKM", "winner_name": "pedro.ferreira", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKPKALVKM", "winner_name": "pedro.ferreira", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKPKALVKM", "winner_name": "pedro.ferreira", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "UKPKALVKM", "winner_name": "pedro.ferreira", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "UKPKALVKM", "winner_name": "pedro.ferreira", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "UKPKALVKM", "winner_name": "pedro.ferreira", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "UKPKALVKM", "winner_name": "pedro.ferreira", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "UKPKALVKM", "winner_name": "pedro.ferreira", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "UKPKALVKM", "winner_name": "pedro.ferreira", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "UKPKALVKM", "winner_name": "pedro.ferreira", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U8M0TKXV0", "loser_name": "kim.stebel" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "UKPKALVKM", "winner_name": "pedro.ferreira", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "UKPKALVKM", "winner_name": "pedro.ferreira", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "UKPKALVKM", "winner_name": "pedro.ferreira", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "UKPKALVKM", "winner_name": "pedro.ferreira", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "UKPKALVKM", "winner_name": "pedro.ferreira", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U8M0TKXV0", "loser_name": "kim.stebel" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U8M0TKXV0", "loser_name": "kim.stebel" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U8M0TKXV0", "loser_name": "kim.stebel" },
  { "winner_id": "U8M0TKXV0", "winner_name": "kim.stebel", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U8M0TKXV0", "winner_name": "kim.stebel", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U8M0TKXV0", "winner_name": "kim.stebel", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UNSL0KBU3", "loser_name": "hannah.dockings" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UNSL0KBU3", "loser_name": "hannah.dockings" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UNSL0KBU3", "loser_name": "hannah.dockings" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U93UKG8CV", "winner_name": "francesca.madeddu", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UNSL0KBU3", "loser_name": "hannah.dockings" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UNSL0KBU3", "loser_name": "hannah.dockings" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKPKALVKM", "loser_name": "pedro.ferreira" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U8M0TKXV0", "loser_name": "kim.stebel" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U8M0TKXV0", "loser_name": "kim.stebel" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "UKMFSMH9U", "loser_name": "jarek.zawila" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "UKMFSMH9U", "winner_name": "jarek.zawila", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U7F7VPWE4", "loser_name": "kieran.sears" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7F7VPWE4", "winner_name": "kieran.sears", "loser_id": "U7BUUBKA9", "loser_name": "billy.cuthbert" },
  { "winner_id": "U7BUUBKA9", "winner_name": "billy.cuthbert", "loser_id": "U93UKG8CV", "loser_name": "francesca.madeddu" },
]

const db = [
  { id: "UKMFSMH9U", name: "jarek.zawila", elo: 1000, wins: 0, losses: 0, history: { x: [], y: [], type: 'line' } },
  { id: "U7BUUBKA9", name: "billy.cuthbert", elo: 1000, wins: 0, losses: 0, history: { x: [], y: [], type: 'line' } },
  { id: "U7F7VPWE4", name: "kieran.sears", elo: 1000, wins: 0, losses: 0, history: { x: [], y: [], type: 'line' } },
  { id: "U93UKG8CV", name: "francesca.madeddu", elo: 1000, wins: 0, losses: 0, history: { x: [], y: [], type: 'line' } },
  { id: "UKPKALVKM", name: "pedro.ferreira", elo: 1000, wins: 0, losses: 0, history: { x: [], y: [], type: 'line' } },
  { id: "UNSL0KBU3", name: "hannah.dockings", elo: 1000, wins: 0, losses: 0, history: { x: [], y: [], type: 'line' } },
  { id: "U8M0TKXV0", name: "kim.stebel", elo: 1000, wins: 0, losses: 0, history: { x: [], y: [], type: 'line' } },
  { id: "U8NPFQK6U", name: "sergio.martin", elo: 1000, wins: 0, losses: 0, history: { x: [], y: [], type: 'line' } },
]

let e = new Elo

data.forEach(game => {
  const winner = _.find(db, e => e.id === game.winner_id)
  const loser = _.find(db, e => e.id === game.loser_id)

  const winnerOld = winner.elo
  const loserOld = loser.elo

  winner.wins++
  winner.elo = e.ifWins(winnerOld, loserOld)
  winner.history.y.push(winner.elo)
  winner.history.x.push(winner.history.y.length - 1)

  loser.losses++
  loser.elo = e.ifLoses(loserOld, winnerOld)
  loser.history.y.push(loser.elo)
  loser.history.x.push(loser.history.y.length - 1)
})


db.sort((a, b) => a.elo < b.elo)

t = new Table

db.forEach(p => {
  t.cell('Player', p.name.split('.')[0])
  t.cell('Wins', p.wins)
  t.cell('Losses', p.losses)
  t.cell('Games', p.wins + p.losses)
  t.cell('Winrate', (p.wins / (p.wins + p.losses) * 100).toFixed(2) + '%')
  t.cell('Elo', p.elo)
  t.newRow()
})
t.sort(['Elo|des'])

console.log(t.toString())











